include:
  - project: 'devops/gitlab/template-cicd'
    ref: '${CICDREF}'
    file: 'php-pipeline.yml'

notify_success:
  when: manual

deploy_bitrix:
  image: reg.gitlab.itnap.ru/devops/gitlab/template-cicd:${CICDREF}
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - echo "${SSH_KEY}" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H -t rsa -T 10 "${INSTANCE_IP}" >> ~/.ssh/known_hosts
    - |
      cat > .env << EOF
      EXPOSE_NGINX_PORT=8080
      COMPOSE_PROJECT_NAME=lims-ulab
      IMAGE_TAG=${IMAGE_TAG:-reg.gitlab.itnap.ru/loki/lims:dev}
      IMAGE_TAG_BITRIX=${IMAGE_TAG_BITRIX:-reg.gitlab.itnap.ru/loki/infra:main}
      TZ=Europe/Moscow
      EOF
  script:
    - scp ./.env support@"${INSTANCE_IP}":/tmp
    - |
      ssh support@"${INSTANCE_IP}" bash -s << EOF
        set -euo pipefail
        sudo cp /tmp/.env /opt/lims-ulab
        cd /opt/lims-ulab
        docker rm bitrix
        COMPOSE_HTTP_TIMEOUT=360 docker-compose up -d bitrix || { echo "Ошибка запуска docker compose"; exit 1; }
        echo "Деплой Bitrix успешно завершён"
      EOF
  tags:
    - ${GL_CI_GITLAB_K8S_RUNNER}
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"

cleanup_and_push_job:
  stage: cleanup-and-push
  image: reg.gitlab.itnap.ru/devops/gitlab/template-cicd:${CICDREF}
  before_script:
    # Установка необходимых инструментов
    - apk add ppp expect
    - chmod +x docker/vpn/64bit/helper/setup.linux.sh
    - docker/vpn/64bit/helper/setup.linux.sh
    - cat docker/vpn/64bit/helper/forticlientsslvpn.install.log
    - cp $connect docker/vpn/64bit/connect.sh
    - chmod +x docker/vpn/64bit/connect.sh
    - cp $ssl docker/vpn/64bit/netyosovia.pfx
    - cp $password docker/vpn/64bit/password.txt
    - ls /builds/loki/lims/docker/vpn/64bit/forticlientsslvpn_cli
    - chmod +x docker/vpn/64bit/forticlientsslvpn
    - chmod +x docker/vpn/64bit/forticlientsslvpn_cli   
    - docker/vpn/64bit/connect.sh &
    - sleep 60
    - cat docker/vpn/64bit/helper/forticlientsslvpn.log
    - cat docker/vpn/64bit/helper/pppd.log
    - git config --global user.name "CI Bot"
    - git config --global user.email "ci@bot.com"
  script:
    - nslookup git.mos.ru/eknd/aisloki
    # - rm -rf docker-compose.yml Makefile .gitlab-ci.yml ./docker .env Dockerfile
    # # Подключение к VPN
    # - openvpn --config $VPN_CONFIG_FILE --auth-user-pass <(echo -e "$VPN_USERNAME\n$VPN_PASSWORD") &
    # - sleep 10 # Даём время для установления VPN-соединения
    # # Клонирование целевого репозитория
    # - git clone $TARGET_REPO_URL target-repo
    # - cd target-repo
    # # Копирование изменённых файлов из текущего репозитория
    # - cp -r ../path/to/modified/files/* .
    # # Коммит и пуш изменений
    # - git add .
    # - git commit -m "Автоматический пуш из CI"
    # - git push origin main
  tags:
    - ${GL_CI_GITLAB_K8S_RUNNER}  