services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    ports:
      - "${EXPOSE_CADVISOR_PORT:-8081}:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    environment:
      TZ: ${TZ}
    depends_on:
      - php
      - webserver
      - promtail
    networks:
      - lims-ulab

  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - bitrix_data:/var/www/bitrix
      - web_data:/var/www/bitrix/ulab
    environment:
      TZ: ${TZ}
    networks:
      - lims-ulab
    restart: unless-stopped
    depends_on:
      db:
        condition: service_started
      bitrix:
        condition: service_completed_successfully
      lims-ulab:
        condition: service_completed_successfully

  webserver:
    container_name: web_server
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      php:
        condition: service_started
      bitrix:
        condition: service_completed_successfully
      lims-ulab:
        condition: service_completed_successfully
    volumes:
      - bitrix_data:/var/www/bitrix
      - web_data:/var/www/bitrix/ulab
      - web_server_bitrix_logs:/var/log/nginx
    ports:
      - "${EXPOSE_NGINX_PORT:-80}:80"
    environment:
      TZ: ${TZ}
    networks:
      - lims-ulab
    restart: unless-stopped

  memcached:
    container_name: memcached
    image: memcached:1.6.24-alpine
    ports:
      - "${INTERFACE:-0.0.0.0}:${EXPOSE_MEMCACHED_PORT:-11211}:11211"
    environment:
      TZ: ${TZ}
    networks:
      - lims-ulab
    restart: unless-stopped

  promtail:
    image: grafana/promtail:main-d5c04e3
    container_name: promtail
    user: "nobody"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/promtail/promtail-config.yaml:/etc/promtail/config.yml
      - web_server_bitrix_logs:/var/log/bitrix:ro
    command: -config.file=/etc/promtail/config.yml
    environment:
      TZ: ${TZ}
    networks:
      - lims-ulab

  db:
    container_name: db
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "${INTERFACE:-0.0.0.0}:${EXPOSE_MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    command: mariadbd
    restart: unless-stopped
    networks:
      - lims-ulab

  bitrix:
    image: ${IMAGE_TAG_BITRIX:-reg.gitlab.itnap.ru/loki/infra:main}
    volumes:
      - bitrix_data:/app
    networks:
      - lims-ulab

  lims-ulab:
    image: ${IMAGE_TAG:-reg.gitlab.itnap.ru/loki/lims:dev}
    volumes:
      - web_data:/app
    networks:
      - lims-ulab

networks:
  lims-ulab:

volumes:
  mysql:
  web_server_bitrix_logs:
  bitrix_data:
  web_data:
