---
services:
  php:
    container_name: php
    build: ./docker/php
    volumes_from:
      - source
    links:
      - db
      - memcached
    environment:
      TZ: ${TZ}
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - lims-ulab

  webserver:
    container_name: web_server
    build: ./docker/nginx
    depends_on:
      - source
    volumes_from:
      - source
    ports:
      - '${INTERFACE}:${EXPOSE_NGINX_PORT}:80'
      - '${INTERFACE}:${EXPOSE_NGINX_SSL_PORT}:443'
    links:
      - php
    environment:
      TZ: ${TZ}
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - lims-ulab


  db:
    container_name: db
    build: ./docker/mysql
#    volumes:
#      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    volumes_from:
      - source
    ports:
      - '${INTERFACE}:${EXPOSE_MYSQL_PORT}:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    command: mysqld --user=root --sql-mode=""
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - lims-ulab

  memcached:
    image: memcached:latest
    container_name: memcached
    volumes_from:
      - source
    ports:
      - '${INTERFACE}:${EXPOSE_MEMCACHED_PORT}:11211'
    environment:
      TZ: ${TZ}
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - lims-ulab

  source:
    image: alpine:latest
    container_name: source
    volumes:
      - ./app:/var/www/bitrix
      - ./db:/var/lib/mysql
      - ./cache:/var/lib/memcached
      - ./logs/nginx:/var/log/nginx
      - ./logs/php:/var/log/php
      - ./logs/db:/var/log/mysql
      - ./logs/memcached:/var/log/memcached
    networks:
      - lims-ulab

networks:
  lims-ulab: