server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.6.173.195:3100/loki/api/v1/push

scrape_configs:
- job_name: docker-qa-logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: docker-qa-logs
      __path__: /var/lib/docker/containers/*/*log

- job_name: bitrix-qa
  static_configs:
  - targets:
      - localhost
    labels:
      job: bitrix-qa
      __path__: /var/log/bitrix/*log

  pipeline_stages:

  - json:
      expressions:
        stream: stream
        attrs: attrs
        tag: attrs.tag

  - regex:
      expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
      source: "tag"

  - labels:
      tag:
      image_name:
      container_name:

