deploy_bitrix:
  image: reg.gitlab.itnap.ru/devops/gitlab/template-cicd:${CICDREF}
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - echo "${SSH_KEY}" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ls -la
    - echo ${INSTANCE_IP}
    - ssh-keyscan -H -t rsa -T 10 "${INSTANCE_IP}" >> ~/.ssh/known_hosts
    - cat > .env << EOF
      EXPOSE_NGINX_PORT=8080
      COMPOSE_PROJECT_NAME=lims-ulab
      IMAGE_TAG=${IMAGE_TAG:-reg.gitlab.itnap.ru/loki/lims:dev}
      IMAGE_TAG_BITRIX=${IMAGE_TAG_BITRIX:-reg.gitlab.itnap.ru/loki/infra:main}
      TZ=Europe/Moscow
      EOF
  script:
    - scp ./.env support@"${INSTANCE_IP}":/tmp
    - |
      ssh support@"${INSTANCE_IP}" bash -s << EOF
        set -euo pipefail
        sudo cp /tmp/.env /opt/lims-ulab
        cd /opt/lims-ulab
        docker rm bitrix
        COMPOSE_HTTP_TIMEOUT=360 docker-compose up -d bitrix || { echo "Ошибка запуска docker compose"; exit 1; }
        echo "Деплой Bitrix успешно завершён"
      EOF
  tags:
    - ${GL_CI_GITLAB_K8S_RUNNER}